Controllers/HMBoatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMSail.Models;
using Microsoft.AspNetCore.Http;

namespace HMSail.Controllers
{
    public class HMBoatsController : Controller
    {
        private readonly SailContext _context;

        public HMBoatsController(SailContext context)
        {
            _context = context;
        }

        // GET: HMBoats
        public async Task<IActionResult> Index(int? memberId)
        {
            if(memberId.HasValue)
            {
                HttpContext.Session.SetInt32("memberId", Convert.ToInt32(memberId.ToString()));
                var sailContext = _context.Boat.Include(b => b.BoatType).Include(b => b.Member).Include(b => b.ParkingCodeNavigation)
                                    .Where(b => b.MemberId == memberId).OrderBy(b => b.BoatClass);
                ViewData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                        .Where(m => m.MemberId == memberId).First().FullName;
                return View(sailContext);
            }
            
            {
                if (HttpContext.Session.GetInt32("memberId") != null)
                {
                    var ids = Convert.ToInt32(HttpContext.Session.GetInt32("memberId"));
                    var sailContext = _context.Boat.Include(b => b.BoatType).Include(b => b.Member).Include(b => b.ParkingCodeNavigation)
                                        .Where(b => b.MemberId == ids).OrderBy(b => b.BoatClass);
                    ViewData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                         .Where(m => m.MemberId == ids).First().FullName;
                    return View(sailContext);
                }
                else
                {
                    TempData["message"] = "Please select a member";
                    return RedirectToAction("Index", "HMMembers");
                }
            }
            //var sailContext = _context.Boat.Include(b => b.BoatType).Include(b => b.Member).Include(b => b.ParkingCodeNavigation);
            //return View(await sailContext.ToListAsync());
        }

        // GET: HMBoats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                       .Where(m => m.MemberId == HttpContext.Session.GetInt32("memberId")).First().FullName;
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boat
                .Include(b => b.BoatType)
                .Include(b => b.Member)
                .Include(b => b.ParkingCodeNavigation)
                .FirstOrDefaultAsync(m => m.BoatId == id);
            if (boat == null)
            {
                return NotFound();
            }

            return View(boat);
        }

        // GET: HMBoats/Create
        public IActionResult Create()
        {
            ViewData["BoatTypeId"] = new SelectList(_context.BoatType.OrderBy(b => b.Name), "BoatTypeId", "Name");
            ViewData["MemberId"] = new SelectList(_context.Member, "MemberId", "FirstName");
            ViewData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                       .Where(m => m.MemberId == HttpContext.Session.GetInt32("memberId")).First().FullName;
            ViewData["ParkingCode"] = new SelectList(_context.Parking.Where(p => p.ActualBoatId == null), "ParkingCode", "ParkingCode");
            return View();
        }

        // POST: HMBoats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BoatId,MemberId,BoatClass,HullColour,SailNumber,HullLength,BoatTypeId,ParkingCode")] Boat boat)
        {
            if (ModelState.IsValid)
            {
                _context.Add(boat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoatTypeId"] = new SelectList(_context.BoatType, "BoatTypeId", "Name", boat.BoatTypeId);
            ViewData["MemberId"] = new SelectList(_context.Member, "MemberId", "FirstName", boat.MemberId);
            ViewData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                       .Where(m => m.MemberId == HttpContext.Session.GetInt32("memberId")).First().FullName;
            return View(boat);
        }

        // GET: HMBoats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boat.FindAsync(id);
            if (boat == null)
            {
                return NotFound();
            }
            ViewData["BoatTypeId"] = new SelectList(_context.BoatType.OrderBy(b => b.Name), "BoatTypeId", "Name", boat.BoatTypeId);
            ViewData["MemberId"] = new SelectList(_context.Member, "MemberId", "FirstName", boat.MemberId);
            ViewData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                       .Where(m => m.MemberId == HttpContext.Session.GetInt32("memberId")).First().FullName;

            if (_context.Boat.FirstOrDefault().ParkingCode == null)
            {
                ViewData["ParkingCode"] = new SelectList(_context.Parking.Where(p => p.ActualBoatId == null), "ParkingCode", "ParkingCode");
            }
            else
            {
                ViewData["ParkingCode"] = new SelectList(_context.Parking.Where(p => p.BoatTypeId == boat.BoatTypeId && p.ActualBoatId == null), "ParkingCode", "ParkingCode");
            }
            return View(boat);
        }

        // POST: HMBoats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BoatId,MemberId,BoatClass,HullColour,SailNumber,HullLength,BoatTypeId,ParkingCode")] Boat boat)
        {
            if (id != boat.BoatId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(boat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoatExists(boat.BoatId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BoatTypeId"] = new SelectList(_context.BoatType, "BoatTypeId", "Name", boat.BoatTypeId);
            ViewData["MemberId"] = new SelectList(_context.Member, "MemberId", "FirstName", boat.MemberId);
            ViewData["ParkingCode"] = new SelectList(_context.Parking, "ParkingCode", "ParkingCode", boat.ParkingCode);
            ViewData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                       .Where(m => m.MemberId == HttpContext.Session.GetInt32("memberId")).First().FullName;
            return View(boat);
        }

        // GET: HMBoats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                       .Where(m => m.MemberId == HttpContext.Session.GetInt32("memberId")).First().FullName;
            if (id == null)
            {
                return NotFound();
            }

            var boat = await _context.Boat
                .Include(b => b.BoatType)
                .Include(b => b.Member)
                .Include(b => b.ParkingCodeNavigation)
                .FirstOrDefaultAsync(m => m.BoatId == id);
            if (boat == null)
            {
                return NotFound();
            }

            return View(boat);
        }

        // POST: HMBoats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                       .Where(m => m.MemberId == HttpContext.Session.GetInt32("memberId")).First().FullName;
            var boat = await _context.Boat.FindAsync(id);
            _context.Boat.Remove(boat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoatExists(int id)
        {
            return _context.Boat.Any(e => e.BoatId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0," />
    <title>@ViewData["Title"] - HMSail</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">       
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img style="float:left;" id="myimage" src="~/images/image.jpg" height="100px" width="150px" /> 
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Crytal Lake Sailing</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="HMMembers" asp-action="Index">Members</a></li>
                    <li><a asp-area="" asp-controller="HMBoats" asp-action="Index">Boats</a></li>
                    <li><a asp-area="" asp-controller="HMParkings" asp-action="Index">Parkings</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div style="margin-top: 8em;" class="container body-content">
        <p style="color:red; font-weight:bold">@TempData["message"]</p> <!-- Temp Data-->
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - <a href="mailto:Htran0276@constogac.on.ca">Hy Minh Tran</a> - Section 6 </p>

            <p class="about">
                <a asp-controller="Home" asp-action="About">About</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a asp-controller="Home" asp-action="Contact">Contact</a>
            </p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>