Assignment 4 source code/Controllers/HMBPBoatTypeController.cs
/*
 File: HMBPBoatTypeColler.cs
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMBPSail.Models;

namespace HMBPSail.Controllers
{
    public class HMBPBoatTypeController : Controller
    {
        private readonly SailContext _context;

        public HMBPBoatTypeController(SailContext context)
        {
            _context = context;
        }

        // GET: HMBPBoatType
        public async Task<IActionResult> Index()
        {
            return View(await _context.BoatType.ToListAsync());
        }

        // GET: HMBPBoatType/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boatType = await _context.BoatType
                .FirstOrDefaultAsync(m => m.BoatTypeId == id);
            if (boatType == null)
            {
                return NotFound();
            }

            return View(boatType);
        }

        // GET: HMBPBoatType/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: HMBPBoatType/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BoatTypeId,Name,Description,Chargeable,Sail,Image")] BoatType boatType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(boatType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(boatType);
        }

        // GET: HMBPBoatType/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boatType = await _context.BoatType.FindAsync(id);
            if (boatType == null)
            {
                return NotFound();
            }
            return View(boatType);
        }

        // POST: HMBPBoatType/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BoatTypeId,Name,Description,Chargeable,Sail,Image")] BoatType boatType)
        {
            if (id != boatType.BoatTypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(boatType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoatTypeExists(boatType.BoatTypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boatType);
        }

        // GET: HMBPBoatType/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boatType = await _context.BoatType
                .FirstOrDefaultAsync(m => m.BoatTypeId == id);
            if (boatType == null)
            {
                return NotFound();
            }

            return View(boatType);
        }

        // POST: HMBPBoatType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var boatType = await _context.BoatType.FindAsync(id);
            _context.BoatType.Remove(boatType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoatTypeExists(int id)
        {
            return _context.BoatType.Any(e => e.BoatTypeId == id);
        }
    }
}

Assignment 4 source code/Controllers/HMBPMembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMBPSail.Models;

namespace HMBPSail.Controllers
{
    public class HMBPMembersController : Controller
    {
        private readonly SailContext _context;

        public HMBPMembersController(SailContext context)
        {
            _context = context;
        }

        // GET: HMBPMembers
        public async Task<IActionResult> Index()
        {
            var sailContext = _context.Member.Include(m => m.ProvinceCodeNavigation).OrderBy(m => m.FullName); // order by fullname
            return View(await sailContext.ToListAsync());
        }

        // GET: HMBPMembers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.ProvinceCodeNavigation)
                .FirstOrDefaultAsync(m => m.MemberId == id);
            TempData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                    .Where(m => m.MemberId == id).First().FullName;
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: HMBPMembers/Create
        public IActionResult Create()
        {
            ViewData["ProvinceCode"] = new SelectList(_context.Province, "ProvinceCode", "ProvinceCode");
            return View();
        }

        // POST: HMBPMembers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MemberId,FullName,FirstName,LastName,SpouseFirstName,SpouseLastName,Street,City,ProvinceCode,PostalCode,HomePhone,Email,YearJoined,Comment,TaskExempt,UseCanadaPost")] Member member)
        {
            // the try catch statement 
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(member);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "New Record Added"; // adding on success tempdata message
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                // on error add model into modelstate
                ModelState.AddModelError("", $"Error on saving create: " + $"{ex.GetBaseException().Message}");
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province, "ProvinceCode", "ProvinceCode", member.ProvinceCode);
            return View(member);
        }

        // GET: HMBPMembers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(p => p.Name), "ProvinceCode", "Name", member.ProvinceCode);
            TempData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                    .Where(m => m.MemberId == id).First().FullName;
            return View(member);
        }

        // POST: HMBPMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MemberId,FullName,FirstName,LastName,SpouseFirstName,SpouseLastName,Street,City,ProvinceCode,PostalCode,HomePhone,Email,YearJoined,Comment,TaskExempt,UseCanadaPost")] Member member)
        {
            if (id != member.MemberId)
            {
                ModelState.AddModelError("", "you're not updating the record you requested");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(member);
                    await _context.SaveChangesAsync();
                    TempData["message"] = "Edit record successful";
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    if (!MemberExists(member.MemberId))
                    {
                        ModelState.AddModelError("", $"memberId is not on file");
                    }
                    else
                    {
                        ModelState.AddModelError("", ex.GetBaseException().Message);
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", $"Update error: {ex.GetBaseException().Message}"); //innermost
                }
                return RedirectToAction(nameof(Index));
            }
            TempData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                    .Where(m => m.MemberId == id).First().FullName;
            ViewData["ProvinceCode"] = new SelectList(_context.Province.OrderBy(p => p.Name), "ProvinceCode", "Name", member.ProvinceCode);
            return View(member);
        }

        // GET: HMBPMembers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Member
                .Include(m => m.ProvinceCodeNavigation)
                .FirstOrDefaultAsync(m => m.MemberId == id);
            if (member == null)
            {
                return NotFound();
            }

            TempData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                    .Where(m => m.MemberId == id).First().FullName;

            return View(member);
        }

        // POST: HMBPMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            TempData["heading"] = _context.Member.Include(m => m.ProvinceCodeNavigation)
                                    .Where(m => m.MemberId == id).First().FullName;
            var member = await _context.Member.FindAsync(id);
            _context.Member.Remove(member);
            await _context.SaveChangesAsync();
            TempData["message"] = "Record deleted successfully";
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(int id)
        {
            return _context.Member.Any(e => e.MemberId == id);
        }
    }
}

Assignment 4 source code/Views/HMBPMembers/Create.cshtml
@model HMBPSail.Models.Member

@{
    ViewData["Title"] = "Create a new record"; // Title
}

<h2>Create a new record</h2> <!--heading-->
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            @*commented out fullName from page*@
            @*<div class="form-group">
                    <label asp-for="FullName" class="control-label"></label> 
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpouseFirstName" class="control-label"></label>
                <input asp-for="SpouseFirstName" class="form-control" />
                <span asp-validation-for="SpouseFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpouseLastName" class="control-label"></label>
                <input asp-for="SpouseLastName" class="form-control" />
                <span asp-validation-for="SpouseLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProvinceCode" class="control-label"></label>
                <input asp-for="ProvinceCode" class="form-control" asp-items="ViewBag.ProvinceCode">
                <span asp-validation-for="ProvinceCode" class="text-danger"></span> @*added span tag*@
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomePhone" class="control-label"></label>
                <input asp-for="HomePhone" class="form-control" />
                <span asp-validation-for="HomePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearJoined" class="control-label"></label>
                <input asp-for="YearJoined" class="form-control" />
                <span asp-validation-for="YearJoined" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="TaskExempt" /> @Html.DisplayNameFor(model => model.TaskExempt)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="UseCanadaPost" /> @Html.DisplayNameFor(model => model.UseCanadaPost)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Assignment 4 source code/Views/HMBPMembers/Delete.cshtml
@model HMBPSail.Models.Member

@{
    ViewData["Title"] = "Delete " + TempData["heading"]; // changed to present Delete ....
}

<h2>@ViewData["Title"]</h2> <!--heading-->


<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SpouseFirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpouseFirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SpouseLastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpouseLastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.YearJoined)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.YearJoined)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaskExempt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskExempt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UseCanadaPost)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UseCanadaPost)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProvinceCodeNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProvinceCodeNavigation.ProvinceCode)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="MemberId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Assignment 4 source code/Views/HMBPMembers/Details.cshtml
@model HMBPSail.Models.Member

@{
    ViewData["Title"] = "Details information about " + TempData["heading"]; // changed to present details about "Details of chesterfield etc...."
}

<h2>@ViewData["Title"]</h2> <!--heading-->

<div>
    <h4>Member</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SpouseFirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpouseFirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SpouseLastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SpouseLastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HomePhone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HomePhone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.YearJoined)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.YearJoined)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TaskExempt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TaskExempt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UseCanadaPost)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UseCanadaPost)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProvinceCodeNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProvinceCodeNavigation.ProvinceCode)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.MemberId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Assignment 4 source code/Views/HMBPMembers/Edit.cshtml
@model HMBPSail.Models.Member

@{
    ViewData["Title"] = "Edit information about " + TempData["heading"]; // changed to present edit infromation of "Edit chesterfield etc...."
}

<h2>@ViewData["Title"]</h2> <!--heading-->

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MemberId" />

            @*commented out fullName*@
            @*<div class="form-group">
                <label asp-for="FullName" class="control-label"></label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>*@

            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpouseFirstName" class="control-label"></label>
                <input asp-for="SpouseFirstName" class="form-control" />
                <span asp-validation-for="SpouseFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpouseLastName" class="control-label"></label>
                <input asp-for="SpouseLastName" class="form-control" />
                <span asp-validation-for="SpouseLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProvinceCode" class="control-label"></label>
                <select asp-for="ProvinceCode" class="form-control" asp-items="ViewBag.ProvinceCode"></select>
                <span asp-validation-for="ProvinceCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HomePhone" class="control-label"></label>
                <input asp-for="HomePhone" class="form-control" />
                <span asp-validation-for="HomePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="YearJoined" class="control-label"></label>
                <input asp-for="YearJoined" class="form-control" />
                <span asp-validation-for="YearJoined" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="TaskExempt" /> @Html.DisplayNameFor(model => model.TaskExempt)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="UseCanadaPost" /> @Html.DisplayNameFor(model => model.UseCanadaPost)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Assignment 4 source code/Views/HMBPMembers/Index.cshtml
@model IEnumerable<HMBPSail.Models.Member>

@{
    ViewData["Title"] = "Member List"; <!-- Title of member list-->
}

<h2>Member List</h2> <!-- heading of member list-->

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HomePhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.YearJoined)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskExempt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UseCanadaPost)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Index" asp-controller="HMBPMemberships" asp-route-memberId="@item.MemberId"
                       asp-route-fullName="@item.FullName">

                        @Html.DisplayFor(modelItem => item.FullName) @*added to  index view*@
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HomePhone) @*added to  index view*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email) @*added to  index view*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.YearJoined) @*added to  index view*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment) @*added to  index view*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaskExempt) @*added to  index view*@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UseCanadaPost) @*added to  index view*@
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.MemberId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.MemberId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.MemberId">Delete</a> |
                    <a asp-area="" asp-controller="HMBPBoatType" asp-action="Index">Show Boats</a>


                </td>
            </tr>
        }
    </tbody>
</table>